# Fundamental concepts

- Intro to tensors
- Getting info from tensors
- Manipulating tensors
- Tensors and Numpy
- Using @tf function to speed up regular Python functions
- Using GPUs with TF
- Excercises





## Intro to Tensors

In [1]:
# Import TF
import tensorflow as tf
print(tf.__version__)

2.4.1


Creating tensors with tf.constant

In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor(ndim)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of a vector
vector.ndim

1

In [6]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check dimension of a matrix
matrix.ndim

2

In [8]:
# Another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                             [5.,5.]], dtype=tf.float16) #specify data type)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 5.,  5.]], dtype=float16)>

In [9]:
# What is the number of dimensions
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                     [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

Notes:
- Scalar: a single number, 0 dimensions
- Vector: a number with direction (ie. speed and direction), 1 dimension
- Matrix: a 2 dimensional array of numbers
- Tensor: an n-dimensional array of numbers (if n=0 scalar, if n=1 vector)

Creating Tensors with tf.Variable

In [12]:
# Create same tensor as above with tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

### Try to change one of the elements in changeable_tensor
changeable_tensor[0] = 7
changeable_tensor

### GIVES AND ERROR

In [13]:
# ...trying other way .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

unchangeable_tensor[0] = 7
unchangeable_tensor

### GIVES AND ERROR

unchangeable_tensor[0].assign(7)
unchangeable_tensor

### GIVES AND ERROR

### Creating Random Tensors (tf.random.Generator.from_seed())

In [14]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
# random_1
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor (.shuffle)

In [15]:
# Suffle a tensor (to avoid bias towards a category, and allow the NN to learn from different categories at the same time)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [16]:
# Shuffle
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [17]:
tf.random.set_seed(42)  # global level
tf.random.shuffle(not_shuffled, seed=42)  # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [18]:
## read TF documentation with random seed generation and practice (use rule 4 better to be consistent every time): https://www.tensorflow.org/api_docs/python/tf/random/set_seed

### Other ways to make tensors (tf.xxxx)

In [19]:
# Create a tensors of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors (tf.constant(numpy_A, shape=(2,3,4)))

The main difference between NumPy arrays and TF tensors is that tensors can be run on a GPU computing

In [21]:
# Turning numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)  # creat a numpy array between 1 to 25
numpy_A

# X = tf.constant(some matrix)  # capital letter for matrix or tensor
# y = tf.constant(vector)  # non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A = tf.constant(numpy_A)   # convertion step
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [23]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [24]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [25]:
2*3*4

24

In [26]:
A = tf.constant(numpy_A, shape=(3,8))
A

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [27]:
A.ndim

2

### Getting information from Tensors
Attributes:
- Shape
- Rank
- Axis or dimension
- Size

In [28]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
rank_4_tensor[0] # 0 axis

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [30]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [31]:
rank_4_tensor.ndim

4

In [32]:
2*3*4*5

120

In [33]:
# Get various tensor attributes
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to integer 120

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


### Indexing tensors

Just like a python list

In [34]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [35]:
# Get first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [36]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [37]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]   # first elements with 1 get flattened except the last one

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [38]:
A

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [39]:
A[:3]

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [40]:
A[:1,:1]

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[1]], dtype=int32)>

In [41]:
# Create a rank 2 sensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                            [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [42]:
rank_2_tensor = tf.constant([[10,7],
                            [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [43]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:2,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [44]:
# Add an extra dimension to our rank 2 sensor
rank_3_sensor = rank_2_tensor[..., tf.newaxis]
rank_3_sensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [45]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # numbers stay the same, just one more dimension

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [46]:
tf.expand_dims(rank_2_tensor, axis=0) # numbers stay the same, just one more dimension

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [47]:
tf.expand_dims(rank_2_tensor, axis=1) # numbers stay the same, just one more dimension

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

Basic Operations
`+`,`-`,`*`,`/`

In [48]:
# Add values to a tensor using the addition operator
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [49]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [50]:
# Multiplication, Subtraction and Division
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [51]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

In [52]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [53]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix Multiplication (tf.matmul and tf.tensordot)

Very common tensor operation in ML

In [54]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [55]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [56]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [57]:
tensor1 = tf.constant ([[1,2,5],   # tensor (3,3)
                        [7,2,1],
                        [3,3,3]])
tensor1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [58]:
tensor2 = tf.constant ([[3,5],  # tensor (3,2)
                       [6,7],
                       [1,8]])
tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [59]:
tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [60]:
# Matrix multiplication with Python operator @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [61]:
tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [62]:
tensor1 @ tensor1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[30, 21, 22],
       [24, 21, 40],
       [33, 21, 27]], dtype=int32)>

tensor2 @ tensor2

#### Error, incompatible size

In [63]:
# let's change the shape of tensor2
tf.reshape(tensor2, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [64]:
tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [65]:
tf.reshape(tensor2, shape=(2,3)) @ tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 45,  98],
       [ 35, 106]], dtype=int32)>

In [66]:
tf.matmul(tf.reshape(tensor2, shape=(2,3)), tensor2) # option 1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 45,  98],
       [ 35, 106]], dtype=int32)>

In [67]:
tf.matmul(tensor2, tf.reshape(tensor2, shape=(2,3))) # option 2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 20, 58],
       [67, 37, 92],
       [59, 13, 70]], dtype=int32)>

In [68]:
# Can do the same with transpose
tensor2, tf.transpose(tensor2), tf.reshape(tensor2, shape=(2,3))   # Reference of transpose and reshape

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 6, 1],
        [5, 7, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 5, 6],
        [7, 1, 8]], dtype=int32)>)

In [69]:
# Try matrix multiplication with transpose
tf.matmul(tf.transpose(tensor2), tensor1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[48, 21, 24],
       [78, 48, 56]], dtype=int32)>

The Dot Product

Matrix Multiplication is also called dot product

- tf.matmul
- tf.tensordot (also know as tensor contraction)

In [70]:
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [71]:
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [72]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [85]:
tf.matmul(tf.transpose(X), Y)  # same as tensordot but without axes

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [74]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [76]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [77]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n")  # extra line

print("Y reshaped to (2,3):")
print(tf.reshape(Y,(2,3)),"\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [78]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally when performing matrix multiplication on two sensors and one of the axes doesn't line up, transpose rather than reshape one of the tensors to satisfy the multiplication rules

### Changing the datatype of a tensor (tf.cast)

In [79]:
tf.__version__

'2.4.1'

In [80]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,1.4])
B.dtype

tf.float32

In [81]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [82]:
# change from float32 to float 16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 1.4], dtype=float16)>,
 tf.float16)

In [83]:
# Change int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [84]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Agrgregating Tensors

Condensing tensors from multipl values to smaller

In [87]:
# New tensor
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [88]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Froms of aggregation:

* Get the minimum 
* Get the maximum 
* Get the mean of a tensor
* Get the sum of a tensor

In [91]:
X # using previously created tensors

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [99]:
X
D
tf.math.minimum(X,D)  # this is between 2 tensors

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ -7, -10],
       [ -7, -10],
       [ -7, -10]], dtype=int32)>

In [95]:
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([96, 16, 31, 16, 12, 63, 87, 41,  6, 70, 43, 34, 81, 42, 29, 50,  8,
       71, 94, 12, 30, 72, 91, 44, 26, 59, 74, 69, 88, 47, 82, 11, 68, 39,
       34, 44, 92,  0, 43, 23, 93, 50, 61, 79, 57, 11, 75, 30, 11,  4])>

In [96]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [98]:
# find the minimmum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [100]:
# find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [101]:
# find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [102]:
# find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2409>

In [111]:
# Find a variance of E tensor
import tensorflow_probability as tfp   # require this module
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=807>

In [123]:
# Find standard deviation of E tensor
stddev = tfp.stats.stddev(tf.cast(E, dtype=tf.float32))  # convertion from int64 to float32 to work
stddev

<tf.Tensor: shape=(), dtype=float32, numpy=28.423014>

In [128]:
tf.math.reduce_variance(tf.cast(E, dtype= tf.float32))  # same result as above variance

<tf.Tensor: shape=(), dtype=float32, numpy=807.8677>

### Find the positional maximum and minimum

In [124]:
tf.math.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [125]:
tf.math.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [130]:
# Create a new tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [132]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [133]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [134]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [136]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [137]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [138]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single '1' dimensions)

In [143]:
# Create a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [144]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [147]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One hot encoding data

In [149]:
# Create a list of indices
some_list = [0,1,2,3] # could be red,green,blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [153]:
# specify custom values for one hot encoding
tf.one_hot(some_list, depth=5, on_value='yes', off_value='no')

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no', b'no'],
       [b'no', b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'no', b'yes', b'no']], dtype=object)>

In [154]:
# specify custom values for one hot encoding
tf.one_hot(some_list, depth=2, on_value='yes', off_value='no')

<tf.Tensor: shape=(4, 2), dtype=string, numpy=
array([[b'yes', b'no'],
       [b'no', b'yes'],
       [b'no', b'no'],
       [b'no', b'no']], dtype=object)>

### Square, log, square root

In [156]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [157]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [159]:
tf.sqrt(tf.cast(H, dtype=tf.float32)) # cast to float first

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [163]:
tf.math.log(tf.cast(H, dtype=tf.float32)) # cast to float first

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [168]:
tf.math.cos(tf.cast(H, dtype=tf.float32)) # practice function

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([ 0.5403023 , -0.4161468 , -0.9899925 , -0.6536436 ,  0.28366217,
        0.96017027,  0.75390226, -0.14550003, -0.91113025], dtype=float32)>

### Tensors and Numpy

TF interacts with Numpy arrays

Note: a TF tensor can run in a GPU for faster processing, and a numpy array...

In [170]:
# create a tensor directly from a numpy array
J = tf.constant(np.array([3,7,10]))
J

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 3,  7, 10])>

In [171]:
# convert a tensor back to numpy array
np.array(J), type(np.array(J))

(array([ 3,  7, 10]), numpy.ndarray)

In [172]:
# convert tensor J to numpy array
J.numpy(), type(J.numpy())

(array([ 3,  7, 10]), numpy.ndarray)

In [174]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [175]:
# default types of each slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# check the dataypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Find access to GPUs

In [1]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Mon Mar  8 18:20:43 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.56       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8    11W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
# If there is access to a CUDA enabled GPU, TF will automatically use it whenever is possible

## Excercises

In [12]:
M = tf.constant(1)  #scalar
M

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [11]:
M.ndim

0

In [13]:
N = tf.constant([1,2]) # vector
N

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [14]:
N.ndim

1

In [20]:
O = tf.constant([[1,2,3],  #matrix
                [4,5,6]])
O

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [21]:
O.ndim

2

In [22]:
P = tf.constant([[[1,2,3],
                [4,5,6],
                [7,8,9]]])
P

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [23]:
P.ndim   # rank

3

In [24]:
P.shape

TensorShape([1, 3, 3])

In [26]:
tf.size(P)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [38]:
Q = tf.constant(tf.random.uniform(shape=[5,300]))
Q

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.4705832 , 0.10465014, 0.67472696, ..., 0.79847276, 0.9825274 ,
        0.63589716],
       [0.14248025, 0.4457128 , 0.8596617 , ..., 0.57797265, 0.0609926 ,
        0.06947792],
       [0.29524326, 0.8429961 , 0.7004008 , ..., 0.7250763 , 0.4682623 ,
        0.65553594],
       [0.00189304, 0.08930182, 0.21642852, ..., 0.01927888, 0.6787634 ,
        0.16780257],
       [0.07886589, 0.9002068 , 0.11936116, ..., 0.75989115, 0.01241755,
        0.20604908]], dtype=float32)>

In [39]:
R = tf.constant(tf.random.uniform(shape=[5,300]))
R

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.8200661 , 0.95410097, 0.35143578, ..., 0.8191551 , 0.2801366 ,
        0.7317569 ],
       [0.7691997 , 0.95632994, 0.46085572, ..., 0.20168781, 0.98227835,
        0.31199706],
       [0.91117656, 0.6265292 , 0.36242592, ..., 0.42847466, 0.07578814,
        0.23531055],
       [0.8200146 , 0.31677353, 0.9864    , ..., 0.84733903, 0.76470137,
        0.48725998],
       [0.3017422 , 0.02341425, 0.19158101, ..., 0.85913765, 0.02390528,
        0.40537083]], dtype=float32)>

In [42]:
tf.matmul(Q,tf.transpose(R))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[82.14198 , 79.940475, 77.03339 , 79.270454, 74.563736],
       [76.502975, 71.055275, 73.121185, 69.09339 , 68.65369 ],
       [75.149826, 75.92602 , 75.5986  , 73.917984, 71.44046 ],
       [74.58125 , 74.46337 , 73.18624 , 73.79591 , 69.42868 ],
       [73.0273  , 73.48295 , 72.13004 , 70.275665, 67.25443 ]],
      dtype=float32)>

In [37]:
R

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.06299388, 0.18538201, 0.56920624, 0.4866011 , 0.5024178 ,
       0.3695197 , 0.09433115, 0.99571645, 0.74045897, 0.05149651,
       0.16213238, 0.48802233, 0.79308915, 0.39151347, 0.06773627,
       0.14564526, 0.39069986, 0.731588  , 0.28697276, 0.62649715,
       0.90870523, 0.4249109 , 0.02911198, 0.04374683, 0.5780051 ,
       0.1864872 , 0.67779446, 0.19693029, 0.06853008, 0.796201  ,
       0.50440025, 0.00357902, 0.28536272, 0.71559703, 0.5771314 ,
       0.5797025 , 0.10486853, 0.16253495, 0.4810568 , 0.6479131 ,
       0.10301781, 0.65794396, 0.58957326, 0.43702304, 0.7626437 ,
       0.50317144, 0.88160837, 0.13135397, 0.61331856, 0.96124077,
       0.8015717 , 0.2988801 , 0.7325076 , 0.0142349 , 0.8114722 ,
       0.1103369 , 0.43065548, 0.30074525, 0.33552408, 0.46150148,
       0.8309543 , 0.45131683, 0.38810778, 0.09784615, 0.70395875,
       0.11199927, 0.9877721 , 0.08158565, 0.1729846 , 0.25931   ,
       0.82117

In [43]:
tf.tensordot(Q,tf.transpose(R),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[82.14198 , 79.940475, 77.03339 , 79.270454, 74.563736],
       [76.502975, 71.055275, 73.121185, 69.09339 , 68.65369 ],
       [75.149826, 75.92602 , 75.5986  , 73.917984, 71.44046 ],
       [74.58125 , 74.46337 , 73.18624 , 73.79591 , 69.42868 ],
       [73.0273  , 73.48295 , 72.13004 , 70.275665, 67.25443 ]],
      dtype=float32)>

In [44]:
S = tf.constant(tf.random.uniform(shape=[224,224,3]))
S

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[9.08134699e-01, 3.75289083e-01, 2.22025752e-01],
        [8.71148467e-01, 2.13998556e-01, 4.36605573e-01],
        [8.80699754e-01, 2.36614108e-01, 2.94582963e-01],
        ...,
        [5.63096523e-01, 4.80108738e-01, 1.11959457e-01],
        [8.39346409e-01, 1.26361012e-01, 9.30603743e-02],
        [7.70224810e-01, 4.60586190e-01, 1.93270683e-01]],

       [[1.65343285e-04, 6.71547174e-01, 8.76376271e-01],
        [5.18836975e-02, 6.23538613e-01, 1.82367802e-01],
        [5.83194494e-01, 4.45314050e-01, 6.86858892e-02],
        ...,
        [4.06238914e-01, 5.24005413e-01, 1.25544786e-01],
        [2.07283974e-01, 9.57589507e-01, 1.53245687e-01],
        [7.41413832e-02, 5.48560619e-02, 1.73826218e-02]],

       [[6.46189809e-01, 3.66714835e-01, 8.67955685e-01],
        [4.16137457e-01, 2.20340133e-01, 8.67474079e-01],
        [5.78316092e-01, 9.26745296e-01, 1.54892206e-02],
        ...,
        [2.36198306e-01, 4.62727

In [49]:
tf.argmax(S)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[149,  94,   6],
       [ 53,  50,  65],
       [144, 111, 108],
       [ 29,  47,  77],
       [199, 130,  44],
       [ 21, 195,  76],
       [202, 173, 213],
       [191, 156, 111],
       [151, 119, 187],
       [ 36,   7,  15],
       [ 78,  46, 132],
       [203,   2, 126],
       [ 87, 193, 154],
       [200, 163, 112],
       [ 83, 186,  26],
       [147,  86, 139],
       [152, 179, 194],
       [ 67, 181, 166],
       [209, 176,  42],
       [151, 106, 136],
       [ 38, 218, 201],
       [187,   5,   6],
       [122,  63, 166],
       [107,   1, 119],
       [180,  77, 182],
       [206,  41, 209],
       [206, 102, 212],
       [185,  35, 205],
       [216,  53, 174],
       [174, 109, 129],
       [150, 124, 107],
       [ 13,  25, 126],
       [106,  43,  79],
       [124,  61, 222],
       [ 46, 132,  32],
       [195, 129, 163],
       [200, 219,  82],
       [203, 215, 195],
       [150,  33,  53],
       [ 37, 155

In [50]:
tf.argmin(S)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[  1,   4,  52],
       [146, 146,  14],
       [ 69, 160,  32],
       [150, 101,  99],
       [  6,  65,  43],
       [160, 220,  65],
       [200,  61,  36],
       [138, 174, 145],
       [178, 101, 178],
       [ 52,  65,  58],
       [ 80,  95, 116],
       [217, 170,  69],
       [213,  93, 107],
       [ 39, 126, 223],
       [ 46,  37,   7],
       [ 35, 207, 115],
       [ 30, 100, 118],
       [ 99,  34, 161],
       [ 52,  68,  12],
       [207, 151, 100],
       [165,  58,  38],
       [189,  81, 208],
       [199, 132, 204],
       [139, 114,  71],
       [105,  93,  26],
       [175,  30,  61],
       [ 64, 206, 196],
       [102,  31,  34],
       [ 17,  14,  63],
       [ 88,  51,  78],
       [194, 153,   5],
       [206,  75, 207],
       [ 92,  25, 164],
       [ 17, 204,  27],
       [179, 193, 139],
       [ 91, 122,  36],
       [138,  33, 141],
       [212, 148, 220],
       [187,  46, 185],
       [160,  66

In [51]:
T = tf.constant(tf.random.uniform(shape=[1,224,224,3]))
T

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.8931999 , 0.01647007, 0.06493306],
         [0.16119003, 0.83912444, 0.3424647 ],
         [0.5179647 , 0.9105128 , 0.929783  ],
         ...,
         [0.91787505, 0.90253377, 0.8376626 ],
         [0.7379042 , 0.6450299 , 0.62335765],
         [0.69037604, 0.49095905, 0.6787394 ]],

        [[0.39466214, 0.7900243 , 0.4837669 ],
         [0.5027441 , 0.5607096 , 0.9163573 ],
         [0.97523737, 0.08511662, 0.23769534],
         ...,
         [0.29764867, 0.5062996 , 0.55800474],
         [0.95395553, 0.5888716 , 0.06120324],
         [0.6883285 , 0.10797656, 0.4364729 ]],

        [[0.56244075, 0.11544311, 0.1804986 ],
         [0.7584281 , 0.35358334, 0.16853261],
         [0.47422266, 0.5700376 , 0.69335604],
         ...,
         [0.87678444, 0.58368516, 0.03208387],
         [0.772534  , 0.20299494, 0.13023722],
         [0.1903081 , 0.127653  , 0.3165599 ]],

        ...,

        [[0.49498856, 0.57833076, 

In [52]:
U = tf.squeeze(T)
U.shape

TensorShape([224, 224, 3])

In [53]:
V = tf.constant([1,2,3,4,5,6,7,8,9,10])
V

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [54]:
tf.argmax(V)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [55]:
V[tf.argmax(V)]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [59]:
tf.one_hot(V, depth=11)

<tf.Tensor: shape=(10, 11), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>