In [2]:
import tensorflow as tf

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test, = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [4]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Flatten(input_shape=(28,28)),
                                    tf.keras.layers.Dense(128, activation='relu'),
                                    tf.keras.layers.Dropout(0.2),
                                    tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.2862829 ,  0.25850868, -0.24553485,  0.18582323,  0.4987527 ,
         0.46032453, -0.51238215,  0.46925724, -0.48438463, -0.13087694]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.0685573 , 0.11820985, 0.07140858, 0.10992255, 0.15031084,
        0.14464426, 0.05468397, 0.14594209, 0.05623662, 0.08008397]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

1.933478

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4798 - accuracy: 0.8622
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1484 - accuracy: 0.9567
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1048 - accuracy: 0.9688
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0851 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0706 - accuracy: 0.9776


In [11]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0738 - accuracy: 0.9768


[0.0738184005022049, 0.9768000245094299]

In [12]:
probability_model = tf.keras.Sequential([
                                         model,
                                         tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.95287626e-08, 1.57155249e-08, 2.58607770e-06, 4.74467561e-05,
        1.32683087e-10, 3.85915598e-07, 1.91687291e-12, 9.99948144e-01,
        1.16646994e-07, 1.28579063e-06],
       [8.37456980e-07, 3.75063132e-06, 9.99992490e-01, 2.39255337e-06,
        1.46607159e-17, 1.45762167e-08, 1.31244519e-07, 6.34174110e-14,
        5.23629581e-07, 1.23136039e-13],
       [3.20208954e-07, 9.99586403e-01, 4.96540924e-05, 8.99776933e-06,
        3.08752678e-05, 1.10093570e-05, 2.30577825e-05, 1.71883556e-04,
        1.15774368e-04, 2.13069416e-06],
       [9.99910712e-01, 3.03841863e-09, 7.59092436e-05, 3.95565785e-08,
        2.30922570e-08, 4.78542961e-06, 3.43256897e-06, 4.02591155e-07,
        1.80591243e-07, 4.45334899e-06],
       [4.75567504e-07, 7.26814031e-09, 6.79777986e-06, 1.29341204e-08,
        9.92219687e-01, 3.84729475e-07, 2.56870999e-06, 2.11253900e-05,
        7.33758085e-08, 7.74887390e-03]], dtype=float32)>